### ISSUE TITLE
Support non-disjoint classes in FightingWords

### ISSUE THREAD

**Issue by amackcrane** [CornellNLP/ConvoKit#188]
The modal application of the Fighting Words method is to compare two disjoint sets of texts to see which words are characteristic of each. However, the fact that the sets should be disjoint is neither specified in ConvoKit's documentation nor imposed in the paper (Monroe et al (2008) p. 385). But it is implied in [the code at the beginning of `FightingWords.fit()`](https://github.com/CornellNLP/ConvoKit/blob/3b0e4a14fdb12e28f29de7609f4b043eaaf3afcc/convokit/fighting_words/fightingWords.py#L201-L206):

```
        class1, class2 = [], []
        for obj in corpus.iter_objs(self.obj_type, selector):
            if class1_func(obj):
                class1.append(obj)
            elif class2_func(obj):
                class2.append(obj)
```

where corpus components are classified by means of two provided functions. This leads to the error `ValueError: class2_func returned 0 valid corpus components` if `class2` is a subset of `class1` (and undocumented behavior if the converse). But this is a useful case when we're comparing more than two sets of texts in a "one-vs-all" manner.

So if I'm understanding correctly, it might make sense to replace the `elif` statement here with a plain `if`.

**Comment by calebchiam** [comment]
Good catch. I think this was a condition we specification we imposed because it helped catch cases of overlaps. Though you're right that FightingWords does not require that the two sets of texts be disjoint -- this is often how it's used in practice to evaluate linguistic patterns in two different communities.

That being said, the lack of commutativity you pointed out is problematic...I'm okay with making this change and having users decide for themselves whether they want disjoint sets of texts. 

Will make the change tomorrow. LMK if you have any thoughts @cristiandnm

**Comment by cristiandnm** [comment]
Great catch!  I agree we should let the user decide.  We could throw a
warning if the two sets are overlapping to help the user realize that this
is a non-standard use
