### ISSUE TITLE
A question about Conversations Gone Awry Dataset - Wikipedia version (CGA WIKI)

### ISSUE THREAD

**Issue by ray204** [CornellNLP/ConvoKit#215]
**I am unable to construct a complete dialogue structure diagram based on the information in the dataset**

On the page https://convokit.cornell.edu/documentation/awry.html , each `Utterance level information` has a property `id` and `reply_to: index of the Utterance to which this Utterance replies to (None if the Utterance is not a reply)`, I tried to build a tree diagram of the conversation, but found the following situation:

1. There are many `utterance` nodes whose parent nodes do not exist in the dataset, i.e., `corpus.has_utterance(utterance.reply_to) is False` (it can be understood that the node replying to it has been deleted when the dataset was created).

2. There are many `utterance` nodes whose parent node is themselves, i.e., `utterance.reply_to == utterance._id` (I don't understand why this situation would occur).

```python
# test code
def test(dataset_name="conversations-gone-awry-corpus"):
    corpus = Corpus(filename=download(dataset_name))
    for utterance in corpus.iter_utterances():
        if utterance.reply_to is None:
            continue
        if not corpus.has_utterance(utterance.reply_to):
            print(f"error: not found parent: {utterance._id}")  # count=1215
        if utterance.reply_to == utterance._id:
            print(f"error: id = reply_to: {utterance._id}")  # count=84
```

In addition, in project https://colab.research.google.com/drive/1SH4iMEHdoH4IovN-b9QOSK4kG4DhAwmb#scrollTo=0SazSyux7KFS, there is a piece of code like this:

```python
# Given a ConvoKit conversation, preprocess each utterance's text by tokenizing and truncating.
# Returns the processed dialog entry where text has been replaced with a list of
# tokens, each no longer than MAX_LENGTH - 1 (to leave space for the EOS token)
def processDialog(voc, dialog):
    processed = []
    for utterance in dialog.iter_utterances():
        # skip the section header, which does not contain conversational content
        if utterance.meta['is_section_header']:
            continue
        tokens = tokenize(utterance.text)
        # replace out-of-vocabulary tokens
        for i in range(len(tokens)):
            if tokens[i] not in voc.word2index:
                tokens[i] = "UNK"
        processed.append({"tokens": tokens, "is_attack": int(utterance.meta['comment_has_personal_attack']), "id": utterance.id})
    return processed

# Load context-reply pairs from the Corpus, optionally filtering to only conversations
# from the specified split (train, val, or test).
# Each conversation, which has N comments (not including the section header) will
# get converted into N-1 comment-reply pairs, one pair for each reply 
# (the first comment does not reply to anything).
# Each comment-reply pair is a tuple consisting of the conversational context
# (that is, all comments prior to the reply), the reply itself, the label (that
# is, whether the reply contained a derailment event), and the comment ID of the
# reply (for later use in re-joining with the ConvoKit corpus).
# The function returns a list of such pairs.
def loadPairs(voc, corpus, split=None, last_only=False):
    pairs = []
    for convo in corpus.iter_conversations():
        # consider only conversations in the specified split of the data
        if split is None or convo.meta['split'] == split:
            dialog = processDialog(voc, convo)
            iter_range = range(1, len(dialog)) if not last_only else [len(dialog)-1]
            for idx in iter_range:
                reply = dialog[idx]["tokens"][:(MAX_LENGTH-1)]
                label = dialog[idx]["is_attack"]
                comment_id = dialog[idx]["id"]
                # gather as context all utterances preceding the reply
                context = [u["tokens"][:(MAX_LENGTH-1)] for u in dialog[:idx]]
                pairs.append((context, reply, label, comment_id))
    return pairs
```

In this code, `dialog.iter_utterances()` can obtain the lis of `utterance_id`, But some of the `utterances` in this list have a reply relationship with each other, but there are also some that are not directly related.

**Comment by jpwchang** [comment]
Thanks for raising this to our attention. Part of this is possibly a bug, but part of it is by design. To explain:

The CGA-WIKI dataset sources its conversations from Wikipedia Talk Pages (hence the name). The thing is, Wikipedia talk pages don't actually have a native concept of a "conversation ID". A talk page, from a technical perspective, just an ordinary Wikipedia page using standard Wikipedia markup, which does not have any functionality for rendering structured conversations. Instead, conversation structure is basically communicated by text formatting, with editors using newlines and signatures to separate "comments", and indentation to indicate "reply structure". The CGA-WIKI corpus gets its "conversation IDs" upstream from WikiConv (https://github.com/conversationai/wikidetox/tree/main/wikiconv), which was a research project that converted talk page conversations to a mostly-well-structured format using heuristics. These heuristics are based on the assumption that editors follow the common practices like indenting replies, but since talk pages are just ordinary Wikipedia markup, there is nothing enforcing these practices and they are not always followed.

For this reason, most of our example code using CGA-WIKI has (following what was done in the source papers) *purposely* decided to disregard the (heuristically-inferred, imperfect) reply-to structure and simply treat the conversation as a linear chain of replies, which we iterate over in order using `iter_utterances`. This is not an arbitrary choice; it is based on our intuition (from looking at many talk page conversations) that regardless of whether or not formatting conventions are followed, talk page conversations typically do not branch, and have a coherent flow when read linearly from top to bottom. For instance, here is an example of a talk page conversation that illustrates this: https://en.wikipedia.org/wiki/Talk:Type_Ia_supernova#Inconsistency_in_source_of_max_light_output?. Here, Spireguy does not indent their second comment, but it reads coherently as a reply to RJH's comment (which *is* indented) - RJH expresses uncertainty and Spireguy offers clarification. This is, of course, *also* a heuristic-based approach and there is room for debate over whether it is more "correct" than using the WikiConv reply-to structures, but both are imperfect ways of trying to recover very messy implicit conversational structure!

In any case, I think the main takeaway from this is that all of that information should probably be documented somewhere in the description of the CGA-WIKI corpus :)

*All of that having been said*, the existence of utterances that appear to reply to themselves definitely *does* look like some kind of bug. I'm not sure what caused it, but right now my best guess is that it arose from some confusion of IDs during the process of consolidating WikiConv comment editing actions. Verifying this will require finding the source conversations in the original WikiConv data. This process will take some time due to the large size of the original WikiConv data, but we'll update again on this thread as soon as we have any findings!
